repos:
-   repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
    -   id: black
        stages: [pre-commit]
        types: [python]
        language_version: python3
    -   id: black-jupyter
        stages: [pre-commit]
        types: [jupyter]
        additional_dependencies: ['black[jupyter]']