name: documentation

on: [push, pull_request, workflow_dispatch]

permissions:
  contents: write

jobs:
  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install dependencies
        run: |
          pip install sphinx sphinx_rtd_theme myst_parser piccolo-theme sphinx-autodoc-typehints
          pip install -e .
      
      - name: Create .nojekyll
        run: |
          touch .nojekyll
          touch docs/.nojekyll
      
      - name: Generate API documentation
        run: |
          cd docs
          sphinx-apidoc -o source/ ../src/academic_metrics -f
      
      - name: Build Documentation
        run: |
          cd docs
          make html
          touch build/html/.nojekyll
      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
        with:
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: docs/build/html
          force_orphan: true